## 创建多段线

资料参考：

[帮助 | ScaleEntity Method (ActiveX) | Autodesk](https://help.autodesk.com/view/OARX/2018/CHS/?guid=GUID-F5A968AB-47BC-4D86-A04D-5985FF217596)

总算实现了。（2021-08-15）

[帮助 | AddPolyline Method (ActiveX) | Autodesk](https://help.autodesk.com/view/OARX/2018/CHS/?guid=GUID-ED02917C-D1D6-46B8-95C6-736163C31362)

[帮助 | AddLightWeightPolyline Method (ActiveX) | Autodesk](https://help.autodesk.com/view/OARX/2018/CHS/?guid=GUID-2003E0A1-5FB5-48A7-8CDA-2804F7C61C1C)

[帮助 | vlax-safearray-fill (AutoLISP/ActiveX) | Autodesk](https://help.autodesk.com/view/OARX/2018/CHS/?guid=GUID-7C2331B4-1A4D-40FF-B59A-D35F7942936B)

[帮助 | SetWidth Method (ActiveX) | Autodesk](https://help.autodesk.com/view/OARX/2018/CHS/?guid=GUID-ED45F9D1-AE03-4DF0-9F2D-2019BD42CD52)

生成多段线代码：

```c
; refactored at 2021-08-15
; pointsList | must be x-y-z, eg. three points List '(1 1 0 1 2 0 2 2 0)
; pointNum | the num of pointsList to minus 1
(defun AddPolylineUtils (pointsList pointNum layerName / acadObj curDoc points modelSpace)
  ;; This example creates a polyline in model space.
  (setq acadObj (vlax-get-acad-object))
  (setq curDoc (vla-get-ActiveDocument acadObj))
  ;; Define the 2D polyline points
  (setq points (vlax-make-safearray vlax-vbDouble (cons 0 pointNum)))
  (vlax-safearray-fill points pointsList)
  ;; Create a lightweight Polyline object in model space
  (if (= (vla-get-activespace curDoc) acModelSpace) 
    (setq modelSpace (vla-get-ModelSpace curDoc)) 
    (setq modelSpace (vla-get-PaperSpace curDoc)) 
  )
  (setq plineObj (vla-AddPolyline modelSpace points))
  (vlax-put-property plineObj 'Layer layerName)
  ; (vla-ZoomAll acadObj)
)

; refactored at 2021-08-15
; pointsList | must be x-y, eg. three points List '(1 1 1 2 2 2)
; pointNum | the num of pointsList to minus 1
(defun AddLWPolylineUtils (pointsList pointNum layerName / acadObj curDoc points modelSpace)
  ;; This example creates a polyline in model space.
  (setq acadObj (vlax-get-acad-object))
  (setq curDoc (vla-get-ActiveDocument acadObj))
  ;; Define the 2D polyline points
  (setq points (vlax-make-safearray vlax-vbDouble (cons 0 pointNum)))
  (vlax-safearray-fill points pointsList)
  ;; Create a lightweight Polyline object in model space
  (if (= (vla-get-activespace curDoc) acModelSpace) 
    (setq modelSpace (vla-get-ModelSpace curDoc)) 
    (setq modelSpace (vla-get-PaperSpace curDoc)) 
  )
  (setq plineObj (vla-AddLightWeightPolyline modelSpace points))
  (vlax-put-property plineObj 'Layer layerName)
  ; (vla-ZoomAll acadObj)
)
```

修改多段线宽度的代码：

```c
; 2021-08-15
(defun SetPolyLineWidthUtils (entityName lineWidth / polyLineObj retCoord segment i j nbr_of_vertices nbr_of_segments)
  (setq polyLineObj (vlax-ename->vla-object entityName))
  ;; Obtain the coordinates of each vertex of the selected polyline.
  ;; The coordinates are returned in an array of points.
  (setq retCoord (vlax-variant-value (vla-get-Coordinates polyLineObj)))
  (setq segment 0
    i (vlax-safearray-get-l-bound retCoord 1)                 ;; Start index of coordinates array
    j (vlax-safearray-get-u-bound retCoord 1)                 ;; End index of coordinates array
    nbr_of_vertices (+ (/ (- j i) 2) 1))                      ;; Number of vertices in the polyline
  ;; Determine the number of segments in the polyline.
  ;; A closed polyline has as many segments as it has vertices.
  ;; An open polyline has one fewer segment than it has vertices.
  ;; Check the Closed property to determine if the polyline is closed.
  (if (= (vla-get-Closed polyLineObj) :vlax-true)
    (setq nbr_of_segments nbr_of_vertices)
    (setq nbr_of_segments (1- nbr_of_vertices))
  )
  ;; Get the width of each segment of the polyline
  (while (>= nbr_of_segments 0)
    (vla-SetWidth polyLineObj segment lineWidth lineWidth)
    ;; Prepare to obtain width of next segment, if any
    (setq i (+ i 2)
          segment (1+ segment)
          nbr_of_segments (1- nbr_of_segments))
  )
  (princ)
)
```

调用举例：

```c
(defun c:foo (/ pointsList)
  (setq pointsList '(1 1 1 2 2 2))
  (AddLWPolylineUtils pointsList 5 "0DataFlow-ZsZPTable")
  (SetPolyLineWidthUtils (entlast) 0.5)
)
```
