# 202108. 自动生成标注对象

首选的概念是排出用 entityData 数据集的方式生成（查看了下数据集的内容比较多，改方法生成比较麻烦）。第一时间想到采用 ActiveX 方式，跟之前实现的自动生成块参照一样。

帮助文档里搜「dimension」找到了：

[帮助 | About Creating Linear Dimensions (VBA/ActiveX) | Autodesk](https://help.autodesk.com/view/OARX/2018/CHS/?guid=GUID-A3624BA2-D98D-4493-9920-19C0B7A2C2A2)

To create a linear dimension, use the AddDimAligned or AddDimRotated method. After you create linear dimensions, you can modify the text, the angle of the text, or the angle of the dimension line. In the following illustrations, the extension line origins are designated explicitly. The resulting dimension line location is also shown:

但这里没有生成 Linear Dimensions 的具体代码，不过 get 到了关键词 AddDimAligned，试着从超级经典的「Object Model」文档那边去搜，在 ModelSpace 对象里，其方法列表里果然找到了 AddDimAligned 方法，大赞。

[帮助 | ModelSpace Collection (ActiveX) | Autodesk](https://help.autodesk.com/view/OARX/2018/CHS/?guid=GUID-C541B6F2-1279-4D1C-8DC0-788F27F644EF#GUID-C541B6F2-1279-4D1C-8DC0-788F27F644EF)

[帮助 | AddDimAligned Method (ActiveX) | Autodesk](https://help.autodesk.com/view/OARX/2018/CHS/?guid=GUID-9F5CE147-3787-4DD9-8028-8E89BF02A357)

这里欣喜的发现同时有 VBA 和 autoLisp 的具体代码。在结合自己之前实现的生成块参照的代码：

```c
; 2021-04-17
(defun InsertBlockByNoPropertyByScaleUtils (insPt blockName layerName scale / acadObj curDoc insertionPnt modelSpace blockRefObj blockAttributes)
  (setq acadObj (vlax-get-acad-object))
  (setq curDoc (vla-get-activedocument acadObj)) 
  (setq insertionPnt (vlax-3d-point insPt))
  (setq modelSpace (vla-get-ModelSpace curDoc))
  (setq blockRefObj (vla-InsertBlock modelSpace insertionPnt blockName scale scale scale 0))
  (vlax-put-property blockRefObj 'Layer layerName)
  (princ)
)
```

完成后的代码：

```c
; 2021-04-19
(defun InsertAlignedDimensionUtils (firstInsPt secondInsPt textInsPt layerName dimensionStyleName / 
                                    acadObj curDoc first3DInsPt second3DInsPt text3DInsPt modelSpace dimObj)
  (setq acadObj (vlax-get-acad-object))
  (setq curDoc (vla-get-activedocument acadObj)) 
  (setq first3DInsPt (vlax-3d-point firstInsPt) 
        second3DInsPt (vlax-3d-point secondInsPt)
        text3DInsPt (vlax-3d-point textInsPt)
  )
  (setq modelSpace (vla-get-ModelSpace curDoc))
  ;; Create an aligned dimension object in model space
  (setq dimObj (vla-AddDimAligned modelSpace first3DInsPt second3DInsPt text3DInsPt))
  (vlax-put-property dimObj 'Layer layerName)
  (vlax-put-property dimObj 'StyleName dimensionStyleName)
  ; (GetVlaObjectPropertyAndMethodUtils dimObj)
  (princ)
)
```

这里有个小插曲。没实现修改标注对象的标注样式，关键问题是样式的属性自己想当然的以为是「dimensionStyle」，是错的。后来想到之前封装了函数可以直接查看一个 ActiveX 对象的所有成员方法和成员属性，找到了标注样式属性名是「StyleName」。（2021-04-19）