# 自动生成块对象

目前找到了两种实现路径。（2021-03-07）

用 ActiveX 实现比原始数据集简单很多，但仅对于块，其他图形对象的自动生成，目前个人还是觉得原始数据集更方便。

## 01. 原始数据集

块参照和块属性是 2 个独立的对象，需要分别生成。

以自动生成管道块为例，

```c
; logic for generate Pipe
(defun c:InsertBlockPipeArrowLeft (/ insPt) 
  (setq insPt (getpoint "\n选取水平管道插入点："))
  (VerifyGsLcBlockByName "PipeArrowLeft")
  (VerifyGsLcLayerByName "DataFlow-Pipe")
  (VerifyGsLcLayerByName "DataFlow-PipeComment")
  (GenerateBlockPipeArrowLeft insPt)
)

(defun GenerateBlockPipeArrowLeft (insPt /) 
  (GenerateBlockReference insPt "PipeArrowLeft" "DataFlow-Pipe") 
  (GenerateLeftBlockAttribute (MoveInsertPosition insPt -20 -1) "VERSION" "" "DataFlow-PipeComment" 1.5 0 1 0)
  (GenerateLeftBlockAttribute (MoveInsertPosition insPt -20 2) "PIPENUM" "xxxx" "0" 3 0 0 0)
  (GenerateLeftBlockAttribute (MoveInsertPosition insPt -20 6) "SUBSTANCE" "" "DataFlow-PipeComment" 1.5 0 0 0)
  (GenerateLeftBlockAttribute (MoveInsertPosition insPt -10 6) "TEMP" "" "DataFlow-PipeComment" 1.5 0 0 0)
  (GenerateLeftBlockAttribute (MoveInsertPosition insPt -6.5 6) "PRESSURE" "" "DataFlow-PipeComment" 1.5 0 0 0) 
  (GenerateLeftBlockAttribute (MoveInsertPosition insPt -20 -5) "PHASE" "" "DataFlow-PipeComment" 1.5 0 1 0)
  (GenerateLeftBlockAttribute (MoveInsertPosition insPt -1 6) "FROM" "" "DataFlow-PipeComment" 1.5 0 0 0)
  (GenerateLeftBlockAttribute (MoveInsertPosition insPt 8 6) "TO" "" "DataFlow-PipeComment" 1.5 0 0 0)
  (GenerateLeftBlockAttribute (MoveInsertPosition insPt -20 -9) "DRAWNUM" "" "DataFlow-PipeComment" 1.5 0 1 0)
  (GenerateLeftBlockAttribute (MoveInsertPosition insPt -20 -7) "INSULATION" "" "DataFlow-PipeComment" 1.5 0 1 0)
  (GenerateLeftBlockAttribute (MoveInsertPosition insPt -20 -3) "PIPECLASSCHANGE" "" "DataFlow-PipeComment" 1.5 0 0 0)
  (GenerateLeftBlockAttribute (MoveInsertPosition insPt -12 -3) "REDUCERINFO" "" "DataFlow-PipeComment" 1.5 0 0 0) 
  (entmake 
    (list (cons 0 "SEQEND") (cons 100 "AcDbEntity"))
  )
  (princ)
)
```

## 02. ActiveX

```c
; logic for generate Pipe
; 2021-03-07
(defun c:InsertBlockPipeArrowLeft (/ insPt) 
  (setq insPt (getpoint "\n选取水平管道插入点："))
  (VerifyGsLcBlockByName "PipeArrowLeft")
  (VerifyGsLcPipeLayer)
  (InsertBlockUtils insPt "PipeArrowLeft" "DataFlow-Pipe" (list (cons 1 "PL1101")))
)

; 2021-03-07
(defun InsertBlockUtils (insPt blockName layerName propertyDictList / acadObj curDoc insertionPnt modelSpace blockRefObj blockAttributes)
  (setq acadObj (vlax-get-acad-object))
  (setq curDoc (vla-get-activedocument acadObj)) 
  (setq insertionPnt (vlax-3d-point insPt))
  (setq modelSpace (vla-get-ModelSpace curDoc))
  (setq blockRefObj (vla-InsertBlock modelSpace insertionPnt blockName 1 1 1 0))
  ;(vlax-dump-object blockRefObj T)
  (vlax-put-property blockRefObj 'Layer layerName)
  (setq blockAttributes (vlax-variant-value (vla-GetAttributes blockRefObj)))
  ; another method get the blockAttributes
  ;(setq blockAttributes (vlax-variant-value (vlax-invoke-method blockRefObj 'GetAttributes)))
  ;(vlax-safearray->list blockAttributes)
  ; setting block property value
  (mapcar '(lambda (x) 
            (vla-put-TextString (vlax-safearray-get-element blockAttributes (car x)) (cdr x))
          ) 
    propertyDictList
  ) 
  ;(vla-ZoomAll acadObj) 
  (princ)
)
```
