## 202109. 自动打开关闭文件

### 01. 参考资料

[帮助 | Open Method (ActiveX) | Autodesk](https://help.autodesk.com/view/OARX/2018/CHS/?guid=GUID-9ED7A548-7978-4BFD-8462-E2FA747E8880)

1『突然意识到，看左侧 ActiveX 方法的展开可以做很多事情。（2021-07-27）』

[帮助 | Close Method (ActiveX) | Autodesk](https://help.autodesk.com/view/OARX/2018/CHS/?guid=GUID-F0135870-7411-42CB-82E6-87509ADF3DFF)

```c
(vl-load-com)
(defun c:Example_Close()
    ;; This example cycles through the documents collection
    ;; and closes all open drawings using the Close method
    ;; except the current drawing.
    (setq acadObj (vlax-get-acad-object))
    (setq curDoc (vla-get-ActiveDocument acadObj))
    (setq docs (vla-get-Documents acadObj))

    ;; Close all open documents and discard changes, except for the current drawing
    (vlax-for doc docs
        (if (/= (vla-get-Name doc) (vla-get-Name curDoc))
	    (progn
	        (alert (strcat "Closing " (vla-get-Name doc) " file."))
                (vla-Close doc :vlax-false)
	    )
        )
    )
)
```

[Open | Lee Mac Programming](http://lee-mac.com/open.html)

[Directory Files | Lee Mac Programming](http://www.lee-mac.com/getallfiles.html)

[帮助 | vl-directory-files (AutoLISP) | Autodesk](https://help.autodesk.com/view/OARX/2018/CHS/?guid=GUID-C28C0CB0-FBBE-4AA8-BAC4-2FF222772514)

[Switch between OPENED drawings (vla-activate) - AutoLISP, Visual LISP & DCL - AutoCAD Forums](https://www.cadtutor.net/forum/topic/50535-switch-between-opened-drawings-vla-activate/)

### 02. 过程记录

已经实现了：1）自动打开特定文件夹下的所有 dwg 文件。2）自动关闭除了当前「活动文件」之前的所有文件，需人为点一下命令。3）自动切换到到特定的一个文件，通过文件名或文件路径，需人为点一下命令。

为啥上面的几个串不起来，即打开文件后读取完数据后自动关闭。感觉是缺一个启动命令的「钩子」。测试了下，自动打开的命令是在第一个文件里跑的，打印信息出来也是在那个文件里。最后打开的那个文件启动不了钩子，命令跑不起来。

### 03. 代码

```c
;; copy code from Lee Mac
;; A wrapper for the 'Open' method of the Shell Object
;; target - [int/str] File, folder or ShellSpecialFolderConstants enum
;; 2021-07-27
(defun OpenOneExternalDwgUtils (target / rtn shl)
  (if (and (or (= 'int (type target)) (setq target (findfile target)))
        (setq shl (vla-getinterfaceobject (vlax-get-acad-object) "shell.application"))
      )
      (progn
        (setq rtn (vl-catch-all-apply 'vlax-invoke (list shl 'open target)))
        (vlax-release-object shl)
        (if (vl-catch-all-error-p rtn)
          (prompt (vl-catch-all-error-message rtn))
          t
        )
      )
  )
)

;; 2021-07-27
(defun OpenCurrentDirAllDwgUtils (/ currentDirList) 
  (setq currentDirList (GetCurrentCADFileDirListUtils))
  (mapcar '(lambda (x) 
            (OpenOneExternalDwgUtils x)
          ) 
    currentDirList
  ) 
)

;; 2021-07-27
(defun GetCurrentCADFileDirListUtils (/ currentDir) 
  (setq currentDir (GetCurrentCADFileDirUtils))
  (mapcar '(lambda (x) 
            (strcat currentDir x)
          ) 
    (vl-directory-files currentDir "*.dwg")
  ) 
)

;; 2021-07-27
;; copy code from autolisp-help
(defun CloseExceptCurrentDwgUtils (/ acadObj curDoc docs)
  ;; This example cycles through the documents collection
  ;; and closes all open drawings using the Close method
  ;; except the current drawing.
  (setq acadObj (vlax-get-acad-object))
  (setq curDoc (vla-get-ActiveDocument acadObj))
  (setq docs (vla-get-Documents acadObj))
  ;; Close all open documents and discard changes, except for the current drawing
  (vlax-for doc docs
    (if (/= (vla-get-Name doc) (vla-get-Name curDoc)) 
      (vla-Close doc :vlax-false)
    )
  )
)

;; 2021-07-28
(defun SwitchDwgByFilePathUtils (acadObj docs FilePath /)
  (setq acadObj (vlax-get-acad-object))
  (setq docs (vla-get-Documents acadObj))
  (vlax-for doc docs
    (if (= (vla-get-fullname doc) FilePath)
      (vla-put-windowstate doc acmax)
      (vla-put-windowstate doc acmin)
    )
  )
)

;; 2021-07-28
(defun SwitchDwgByFileNamehUtils (acadObj docs FileName /)
  (setq acadObj (vlax-get-acad-object))
  (setq docs (vla-get-Documents acadObj))
  (vlax-for doc docs
    (if (= (vla-get-Name doc) FileName)
      (vla-put-windowstate doc acmax)
      (vla-put-windowstate doc acmin)
    )
  )
)
```