## 布置图设备自动标准

### 过程记录

前提要有图签、建筑的轴线号块。

思路：

1、框选设备后，通过设备的位置匹配到这些设备的所在图框（图签），在根据图签定位（A0 图幅范围）该楼层所有的轴线数据（横向和纵向）。

2、以横向标注为例。通过轴线数据按一个跨距将所选的设备分组。

注意事项：

1、不要有，带有轴线号的剖面图，否者会造成干扰。有剖面的时候先移除图框。

### 参考资料

### 问题汇总

#### 标注自动关联

解决办法：调用 CAD 原生的标注命令。1）先设置系统变量 DIMASSOC，确保后面生成的标注是关联的。2）生成完后切换到数据流的标注。

自己封装的底层函数 InsertHorizontalRotatedDimensionUtils 生成的标注是没法自动关联的。一定要自动关联，为后续自动调整设备间距做准备。

[使用标注关联性的步骤 | AutoCAD 2019 | Autodesk Knowledge Network](https://knowledge.autodesk.com/zh-hans/support/autocad/learn-explore/caas/CloudHelp/cloudhelp/2019/CHS/AutoCAD-Core/files/GUID-04334508-47C9-43E3-875C-DD5FEC9F9930-htm.html)

[About Associative Dimensions | AutoCAD | Autodesk Knowledge Network](https://knowledge.autodesk.com/support/autocad/getting-started/caas/CloudHelp/cloudhelp/2018/ENU/AutoCAD-Core/files/GUID-8B7E8C96-C30D-409E-881E-7942871E80DA-htm.html?_ga=2.117200645.2071188051.1646438710-1950140929.1634048896)

CAD 原生有个命令 dimreassociate 重新做关联，但目前基本没成功过，应该是用法有问题。

目前找到的信息是，关联标准跟普通对象比对个一个字典对象。对比裸的标准数据和带关联的标准数据：

 ```
 ((-1 . <图元名: 7ff4f7067f60>) (0 . "DIMENSION") (330 . <图元名: 7ff4f74039f0>) (5 . "EDBFE") (100 . "AcDbEntity") (67 . 0) (410 . "Model") (8 . "00修改20220221") (100 . "AcDbDimension") (280 . 0) (2 . "*D1386") (10 387759.0 -749383.0 0.0) (11 383484.0 -749133.0 0.0) (12 0.0 0.0 0.0) (70 . 32) (1 . "") (71 . 5) (72 . 1) (41 . 1.0) (42 . 8550.58) (73 . 0) (74 . 0) (75 . 0) (52 . 0.0) (53 . 0.0) (54 . 0.0) (51 . 0.0) (210 0.0 0.0 1.0) (3 . "1-100") (100 . "AcDbAlignedDimension") (13 379208.0 -744862.0 0.0) (14 387759.0 -744862.0 0.0) (15 0.0 0.0 0.0) (16 0.0 0.0 0.0) (40 . 0.0) (50 . 0.0) (100 . "AcDbRotatedDimension"))

((-1 . <图元名: 7ff4f7067f60>) (0 . "DIMENSION") (5 . "EDBFE") (102 . "{ACAD_XDICTIONARY") (360 . <图元名: 7ff4f70716e0>) (102 . "}") (102 . "{ACAD_REACTORS") (330 . <图元名: 7ff4f7071800>) (102 . "}") (330 . <图元名: 7ff4f74039f0>) (100 . "AcDbEntity") (67 . 0) (410 . "Model") (8 . "00修改20220221") (100 . "AcDbDimension") (280 . 0) (2 . "*D1386") (10 387759.0 -749383.0 0.0) (11 383484.0 -749133.0 0.0) (12 0.0 0.0 0.0) (70 . 32) (1 . "") (71 . 5) (72 . 1) (41 . 1.0) (42 . 8550.58) (73 . 0) (74 . 0) (75 . 0) (52 . 0.0) (53 . 0.0) (54 . 0.0) (51 . 0.0) (210 0.0 0.0 1.0) (3 . "1-100") (100 . "AcDbAlignedDimension") (13 379208.0 -744862.0 0.0) (14 387759.0 -744862.0 0.0) (15 0.0 0.0 0.0) (16 0.0 0.0 0.0) (40 . 0.0) (50 . 0.0) (100 . "AcDbRotatedDimension"))
 ```
 
国外有个人尝试自己加字典实现了：一根直线的标注，原来裸的标准自动重新关联上了。代码复制到了 forked 专区，函数名为 ForkDimlinearAssociative。

[Making dimlinear associative - AutoLISP, Visual LISP & DCL - AutoCAD Forums](https://www.cadtutor.net/forum/topic/47145-making-dimlinear-associative/)

另外一个文章讲解了底层技术：

[Understanding how dimensions are associated with objects - AutoCAD Tips Blog](https://allaboutcad.com/understanding-how-dimensions-are-associated-with-objects/)

这个作者之前有本 CAD 的书籍「2021063AutoCAD-2015-and-AutoCAD-LT-2015-Bible」已经下载过，通过文章发现她的水平应该蛮高的，那么其书籍应该也不错，要去研读。（2022-03-05）

### 代码

复制来的一份底层实现自动关联一根直线标注的代码：

```
; [Making dimlinear associative - AutoLISP, Visual LISP & DCL - AutoCAD Forums](https://www.cadtutor.net/forum/topic/47145-making-dimlinear-associative/)
; 这个函数目前有效的场景，一个直线标注，之前没有做标注关联，可以重新关联 2022-03-04
(defun ForkDimlinearAssociative ( / _dimension _object _extensiondictionary _dimassoc _number _list )
 (if
   (and (setq _dimension (car (entsel "\nSpecify Dimension: ")))
     (or (wcmatch (cdadr (setq _dimension (entget _dimension))) "*DIMENSION*")
        (alert "You must select a dimension to continue!")
     )
     (setq _object (car (entsel "\nSpecify line associate with: ")))
     (or (wcmatch (cdadr (entget _object)) "LINE")
        (alert "You must select a Line to continue!")
     )
   )
   (progn
     (setq _extensiondictionary 
       (handent 
         (vla-get-handle 
           (vla-getextensiondictionary 
             (vlax-ename->vla-object (cdar _dimension))
           )
         )
       )
     )
     (setq _dimassoc
       (entmakex
         (list
           (cons 0 "DIMASSOC")
           (cons 100 "AcDbDimAssoc")
           (cons 330 (cdar _dimension))
           (cons 90 3)
           (cons 70 0)
           (cons 71 0)
           (cons 1 "AcDbOsnapPointRef")
           (cons 72 1)
           (cons 331 _object)
           (cons 73 13)
           (cons 91 3)
           (cons 40 1.0)
           (cons 10 '(0.0 0.0 2.0e+050))
           (cons 75 0)
           (cons 1 "AcDbOsnapPointRef")
           (cons 331 _object)
           (cons 72 1)
           (cons 73 2)
           (cons 91 3)
           (cons 40 1.0)
           (cons 10 '(0.0 0.0 2.0e+050))
           (cons 75 0)
         )
       )
     )
     (entmod 
       (append (entget _extensiondictionary)
         (list (cons 3 "ACAD_DIMASSOC") (cons 360 _dimassoc))
       )
     )
     (setq _number (vl-position (assoc 330 _dimension) _dimension))
     (repeat _number
       (setq _list (cons (nth (setq _number (1- _number)) _dimension) _list))
     )
     (entmod
       (append _list
         (list '(102 . "{ACAD_XDICTIONARY") (cons 330 _extensiondictionary) '(102 . "}") 
           '(102 . "{ACAD_REACTORS") (cons 330  _dimassoc) '(102 . "}")
         )
         (member (assoc 330 _dimension) _dimension)
       )
     )
   )
 ) (princ)
)
```

